# Abdullah Khan

# Compile and compiler flags:
CC = cc
CFLAGS = -Wall -std=c11 -pedantic
DEBUG = -g

all:
	make maketemp

maketemp:
	$(CC) maketemp.c -o maketemp $(CFLAGS)

clean:
	(rm -f *.o;)
	(rm -f *.out;)
	(rm -f maketemp;)
