# Abdullah Khan

# Compile and compiler flags:
CC = cc
CFLAGS = -Wall -std=c11 -pedantic
DEBUG = -g

all:
	make traverse

traverse:
	$(CC) traverse.c -o traverse $(CFLAGS)

clean:
	(rm -f *.o;)
	(rm -f *.out;)
	(rm -f traverse;)
