# Abdullah Khan

# Compile and compiler flags:
CC = cc
CFLAGS = -Wall -std=c11 -pedantic
DEBUG = -g

all:
	make jmp_test

jmp_test:
	$(CC) jmp_test.c -o jmptest $(CFLAGS)

clean:
	(rm -f *.o;)
	(rm -f *.out;)
	(rm -f jmptest;)
